# Generated by Django 2.2.6 on 2019-10-15 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AddField(
            model_name='event',
            name='shortDescription',
            field=models.CharField(default='', max_length=200, verbose_name='Короткое описание'),
        ),
        migrations.AddField(
            model_name='news',
            name='shortDescription',
            field=models.CharField(default='', max_length=200, verbose_name='Короткое описание'),
        ),
    ]
